//! # Planner
//!
//! The planner builds and optimizes an execution plan based on a SQL
//! statement's Abstract Syntax Tree (AST) generated by the parser.

#![allow(clippy::module_inception)]

mod optimizer;
mod plan;
mod planner;
